#!/usr/bin/env python3
"""
Audit Obsidian notes to identify generation source and mapping to PDFs.

This script scans the Lifegames vault to:
- Identify which notes were generated by Claude Code vs other sources
- Map notes to their corresponding PDF attachments
- Detect orphaned notes (no PDF) or orphaned PDFs (no note)
- Generate comprehensive audit report for reprocessing decisions
"""

import os
import re
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from collections import defaultdict

class NoteAuditor:
    def __init__(self, vault_path: str = "Lifegames"):
        self.vault_path = Path(vault_path)
        self.attachments_path = self.vault_path / "Attachments"

        # Results storage
        self.notes: List[Dict] = []
        self.pdfs: Dict[str, Path] = {}  # hash -> path
        self.stats = defaultdict(int)

    def parse_frontmatter(self, content: str) -> Optional[Dict]:
        """Extract YAML frontmatter from markdown content."""
        match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
        if not match:
            return None

        frontmatter = {}
        yaml_content = match.group(1)

        # Parse key fields (simple parser, not full YAML)
        for line in yaml_content.split('\n'):
            if ':' in line:
                key, value = line.split(':', 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")

                if key in ['file_hash', 'filename', 'title', 'source', 'date', 'generated_by', 'generated_at']:
                    frontmatter[key] = value

        return frontmatter

    def detect_generation_source(self, content: str) -> str:
        """Detect if note was generated by Claude Code or other source."""
        # Check for explicit marker
        if 'generated_by' in self.parse_frontmatter(content) or {}:
            return self.parse_frontmatter(content).get('generated_by', 'unknown')

        # Check for Claude Code signature
        if '🤖 Generated with [Claude Code]' in content:
            return 'claude-code'

        # Check for patterns suggesting other LLMs
        if 'Generated by' in content or 'AI-generated' in content:
            return 'other-llm'

        # Check structure patterns
        frontmatter = self.parse_frontmatter(content)
        if frontmatter and 'file_hash' in frontmatter and 'cssclass' in content:
            return 'claude-code-probable'

        return 'manual-or-unknown'

    def extract_user_content(self, content: str) -> Dict[str, str]:
        """Extract user-added sections that should be preserved."""
        sections = {}

        # Extract Linked Concepts section
        linked_match = re.search(
            r'## Linked Concepts\s*\n(.*?)(?=\n## |$)',
            content,
            re.DOTALL
        )
        if linked_match:
            sections['linked_concepts'] = linked_match.group(1).strip()

        # Extract Notes section
        notes_match = re.search(
            r'## Notes\s*\n(.*?)(?=\n## |$)',
            content,
            re.DOTALL
        )
        if notes_match:
            sections['notes'] = notes_match.group(1).strip()

        return sections

    def find_pdf_for_note(self, frontmatter: Dict) -> Optional[Path]:
        """Find the PDF attachment corresponding to a note."""
        if not frontmatter:
            return None

        # Try file_hash first
        file_hash = frontmatter.get('file_hash') or frontmatter.get('filename')
        if file_hash:
            # Search in all attachment subdirectories
            for pdf_path in self.attachments_path.rglob(f"{file_hash}.pdf"):
                return pdf_path

        return None

    def scan_notes(self):
        """Scan all markdown notes in vault."""
        self.stats['total_notes'] = 0

        # Scan top-level notes
        for md_file in self.vault_path.glob("*.md"):
            self._process_note(md_file)

        # Scan Reviewed subfolder
        reviewed_path = self.vault_path / "Reviewed"
        if reviewed_path.exists():
            for md_file in reviewed_path.glob("*.md"):
                self._process_note(md_file)

    def _process_note(self, md_path: Path):
        """Process a single note file."""
        self.stats['total_notes'] += 1

        try:
            content = md_path.read_text(encoding='utf-8')
        except Exception as e:
            self.notes.append({
                'path': str(md_path),
                'error': f'Failed to read: {e}',
                'status': 'error'
            })
            self.stats['errors'] += 1
            return

        frontmatter = self.parse_frontmatter(content)
        generation_source = self.detect_generation_source(content)
        user_content = self.extract_user_content(content)
        pdf_path = self.find_pdf_for_note(frontmatter) if frontmatter else None

        # Determine status
        status = 'ok'
        issues = []

        if not frontmatter:
            issues.append('no_frontmatter')
            status = 'needs_attention'

        if not pdf_path:
            issues.append('pdf_missing')
            status = 'needs_attention'

        if generation_source in ['other-llm', 'manual-or-unknown']:
            issues.append('non_claude_generation')

        # Check if user has added content
        has_user_content = any(
            section and section.strip() and '<!-- For' not in section
            for section in user_content.values()
        )

        note_data = {
            'path': str(md_path.relative_to(self.vault_path)),
            'title': frontmatter.get('title', 'NO TITLE') if frontmatter else 'NO TITLE',
            'file_hash': frontmatter.get('file_hash') if frontmatter else None,
            'generation_source': generation_source,
            'pdf_path': str(pdf_path.relative_to(self.vault_path)) if pdf_path else None,
            'has_user_content': has_user_content,
            'user_content_sections': list(user_content.keys()) if has_user_content else [],
            'status': status,
            'issues': issues,
            'file_size': md_path.stat().st_size
        }

        self.notes.append(note_data)

        # Update stats
        self.stats[f'generation_{generation_source}'] += 1
        if pdf_path:
            self.stats['notes_with_pdf'] += 1
        else:
            self.stats['notes_without_pdf'] += 1
        if has_user_content:
            self.stats['notes_with_user_content'] += 1

    def scan_pdfs(self):
        """Scan all PDF attachments."""
        self.stats['total_pdfs'] = 0

        if not self.attachments_path.exists():
            return

        for pdf_path in self.attachments_path.rglob("*.pdf"):
            self.stats['total_pdfs'] += 1
            file_hash = pdf_path.stem  # filename without extension
            self.pdfs[file_hash] = pdf_path

    def find_orphaned_pdfs(self) -> List[Dict]:
        """Find PDFs without corresponding notes."""
        orphaned = []
        note_hashes = {note['file_hash'] for note in self.notes if note.get('file_hash')}

        for file_hash, pdf_path in self.pdfs.items():
            if file_hash not in note_hashes:
                orphaned.append({
                    'file_hash': file_hash,
                    'pdf_path': str(pdf_path.relative_to(self.vault_path)),
                    'file_size': pdf_path.stat().st_size
                })

        return orphaned

    def generate_report(self) -> Dict:
        """Generate comprehensive audit report."""
        orphaned_pdfs = self.find_orphaned_pdfs()
        self.stats['orphaned_pdfs'] = len(orphaned_pdfs)

        # Categorize notes for reprocessing recommendations
        needs_reprocessing = [
            note for note in self.notes
            if note['generation_source'] in ['other-llm', 'manual-or-unknown', 'claude-code-probable']
            and note['pdf_path']  # Only if PDF exists
        ]

        report = {
            'summary': dict(self.stats),
            'notes': self.notes,
            'orphaned_pdfs': orphaned_pdfs,
            'reprocessing_recommendations': {
                'count': len(needs_reprocessing),
                'notes': needs_reprocessing
            }
        }

        return report

    def print_summary(self, report: Dict):
        """Print human-readable summary."""
        stats = report['summary']

        print("=" * 70)
        print("OBSIDIAN VAULT AUDIT REPORT")
        print("=" * 70)
        print(f"\n📊 OVERALL STATISTICS")
        print(f"  Total Notes:          {stats.get('total_notes', 0)}")
        print(f"  Total PDFs:           {stats.get('total_pdfs', 0)}")
        print(f"  Notes with PDF:       {stats.get('notes_with_pdf', 0)}")
        print(f"  Notes without PDF:    {stats.get('notes_without_pdf', 0)}")
        print(f"  Orphaned PDFs:        {stats.get('orphaned_pdfs', 0)}")
        print(f"  Notes with user edits:{stats.get('notes_with_user_content', 0)}")

        print(f"\n🤖 GENERATION SOURCE")
        print(f"  Claude Code:          {stats.get('generation_claude-code', 0)}")
        print(f"  Claude Code (probable):{stats.get('generation_claude-code-probable', 0)}")
        print(f"  Other LLM:            {stats.get('generation_other-llm', 0)}")
        print(f"  Manual/Unknown:       {stats.get('generation_manual-or-unknown', 0)}")

        print(f"\n🔄 REPROCESSING RECOMMENDATIONS")
        recs = report['reprocessing_recommendations']
        print(f"  Recommended count:    {recs['count']}")

        if recs['count'] > 0:
            print(f"\n  Top candidates:")
            for i, note in enumerate(recs['notes'][:10], 1):
                print(f"    {i}. {note['title'][:60]}")
                print(f"       Source: {note['generation_source']}")
                if note['has_user_content']:
                    print(f"       ⚠️  HAS USER CONTENT - preserve: {', '.join(note['user_content_sections'])}")

        if report['orphaned_pdfs']:
            print(f"\n⚠️  ORPHANED PDFs (no corresponding notes):")
            for pdf in report['orphaned_pdfs'][:5]:
                print(f"    - {pdf['pdf_path']}")
            if len(report['orphaned_pdfs']) > 5:
                print(f"    ... and {len(report['orphaned_pdfs']) - 5} more")

        print("\n" + "=" * 70)

def main():
    import sys
    import argparse

    parser = argparse.ArgumentParser(description='Audit Obsidian notes vault')
    parser.add_argument('--vault', default='Lifegames', help='Path to vault')
    parser.add_argument('--json', action='store_true', help='Output JSON report')
    parser.add_argument('--output', help='Save report to file')
    args = parser.parse_args()

    auditor = NoteAuditor(args.vault)

    print("🔍 Scanning notes...")
    auditor.scan_notes()

    print("📄 Scanning PDFs...")
    auditor.scan_pdfs()

    print("📊 Generating report...\n")
    report = auditor.generate_report()

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        auditor.print_summary(report)

    if args.output:
        output_path = Path(args.output)
        output_path.write_text(json.dumps(report, indent=2))
        print(f"\n✅ Full report saved to: {output_path}")

if __name__ == '__main__':
    main()
